### PR TITLE
Update change_list.js

### PR DESCRIPTION
**Pull request by SalmanGill110**
'search-filter-mptt' class does not exist in template.  Causing filtering failure. 
Either change class in template or accept this.

### CODE REVIEW

**Comment by farridav** [comment]
Change list mptt is there when the third party django app Mptt is used, I hadn't expected it to break when the app is not installed.


How does it break for you ?

**Comment by SalmanGill110** [comment]
If you add filters to admin. Filters does not apply. 
choices variable always selects date:today as selected=true. I.e. changing values in filter drop down does not reach backend.

**Comment by farridav** [comment]
I think it might be to do with this being commented out https://github.com/farridav/django-jazzmin/blob/master/jazzmin/static/jazzmin/js/change_list.js#L27

I'm not sure why that change was made, perhaps it was done by accident, I'll seenifni can get a hotfix in today, in the meantime you could put this into some custom js

```
$(document).ready(function () {
    const $ele = $('.search-filter');
    $ele.search_filters();
    $ele.select2({ width: '100%' });
});
```

I'll update this ticket once I've got a fix confirmed and shipped

**Comment by SalmanGill110** [comment]
👍 makes sense..

**Comment by farridav** [comment]
Closing in favour of https://github.com/farridav/django-jazzmin/pull/239

**Pull request closed without merging**
