### PR TITLE
WIP: nested-admin

### PR DESCRIPTION
**Pull request by Laityned**
Initial design for supporting django-nested-admin

Screenshots:
image
image

### CODE REVIEW

**Comment by pierreben** [comment]
Hi,

This would be a totally amazing feature to include in jazzmin as django-nested-admin is really essential in some specific cases.

@farridav , do you remember what was missing to terminate your work on this PR ?

Any way I can contribute to help on this ? For now I will override the templates in my project to test what you were working on and I'm sure I can give some feedbacks.

**Comment by kaizen-cmd** [comment]
Hi @pierreben , did you manage to override the template and get the nested admin working with jazzmin?

**Comment by Laityned** [comment]
Some feedback would be amazing!

**Comment by pierreben** [comment]
Sorry, I'm so busy these days and I had no time to work on it so far but, to give a first feedback, for now I've included the modified files (nested-admin/jazzmin.css, nested-admin/sortable.js, templates/nesting/admin/inlines/includes/inline.html and templates/nesting/admin/inlines/stacked.html) in my project and it works quite well for stacked inlines (not for tabular). 
It's probably not perfect but sufficient for my current need. 
I hope I (or anybody else) will have the time soon to continue this amazing WIP.

**Comment by mrfoggg** [comment]
Expect support or not?

**Comment by farridav** [comment]
This is going to require some input from someone other than myself I'm
afraid.

As always, I'm more than happy to review the finished implementation, and
do a little QA.

**Comment by katiam2** [comment]
Hey everyone! 
This PR from 2021 shows great effort! However, since it still needs some work and has been inactive for a while, I think it's best to close it for now. We are looking forward to see your contributions again!

**Pull request closed without merging**
