### PR TITLE
Release v2.6.1 of Django-Jazzmin

### PR DESCRIPTION
**Pull request by jamesgilmorelyst**
Adds support for Django 4.2

Changes:
- Remove errant “sourceMappingURL” referencing a non-existent file (@codyfletcher) (#474)

### CODE REVIEW

**Comment by jamesgilmorelyst** [comment]
@farridav @TysonRV, did you mind reviewing this PR, please, so we can add support for Django 4.2?

**Comment by farridav** [comment]
Hi @jamesgilmorelyst thanks for your PR, as you can tell, I've not had much time to work on jazzmin recently, and every time I do get a little bit (like now), I see that we have so many pull requests (which is good), and also a lot of issues (most of which were asking about providing integration support for other django packages that toy with the admin)

As a result of this, I'm often overwhelmed with the backlog of work (and also that of other commitments), and do nothing instead (which is understandably not ideal) and i think @TysonRV is also not in a position to help maintain.

Putting a new release out is easy enough, especially if there are unreleased changes in `main`, though really I need some help in triaging issues so i can get back to regular updates, releases and enhancements, which likely will require some outside help...

**Comment by jamesgilmorelyst** [comment]
Thanks, @farridav. Yeah, I can imagine how overwhelming this project might be after seeing how many issues/PRs there are.

I am happy to help triage issues so that regular updates on this project can resume. Let me know where I can help with this project.

**Comment by jamesgilmorelyst** [comment]
@farridav Also, there was an issue with the build process, which seems to be related to the Ubuntu image being used no longer supporting 3.6 of PY. To maintain support for now, it was recommended to pin the image to a known working version.

Did you mind re-approving, please? (sorry for the hassle)

https://github.com/farridav/django-jazzmin/actions/runs/8374469998

**Comment by jamesgilmorelyst** [comment]
@farridav sorry for the back and forth, but the GHA failed again - https://github.com/farridav/django-jazzmin/actions/runs/8376078256/job/22936795892
```
Error: ERROR: Could not find a version that satisfies the requirement importlib-metadata==4.13.0 
```
I'm not really sure why this is needed, and running locally with/without this package on tox doesn't seem to be required. So, I've removed it. The commit this was added doesn't seem to add any context to why this was needed.

I've also fixed a bug in the test for v4.8 of Django, which added a new `date` widget.

Tox passes locally for me now. Do you mind approving again, please, to check GHA is also happy, please?

**Comment by farridav** [comment]
No worries, I appreciate you taking the time to help out, and will find a way to onboard you to the maintainers if you have spare time going forwards .

**Comment by jamesgilmorelyst** [comment]
Thanks, @farridav. I'm happy to help, and it will be great to be able to help maintain this package.

I probably should have done this earlier, but I've managed to get the GHA issues sorted now by running this on my forked repo. So, hopefully, this time, GHA will pass!

**Pull request merged**
